"""empty message

Revision ID: 58a9ae2bb58f
Revises: b67e4864ae18
Create Date: 2018-08-11 17:50:35.924812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58a9ae2bb58f'
down_revision = 'b67e4864ae18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_title', table_name='event')
    op.create_index(op.f('ix_event_title'), 'event', ['title'], unique=False)
    op.add_column('member', sa.Column('is_executive', sa.Boolean(), nullable=True))
    op.add_column('member', sa.Column('username', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_member_is_executive'), 'member', ['is_executive'], unique=False)
    op.create_index(op.f('ix_member_username'), 'member', ['username'], unique=True)
    op.drop_index('ix_member_is_exectuive', table_name='member')
    op.drop_column('member', 'is_exectuive')
    op.drop_index('ix_project_title', table_name='project')
    op.create_index(op.f('ix_project_title'), 'project', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_title'), table_name='project')
    op.create_index('ix_project_title', 'project', ['title'], unique=1)
    op.add_column('member', sa.Column('is_exectuive', sa.BOOLEAN(), nullable=True))
    op.create_index('ix_member_is_exectuive', 'member', ['is_exectuive'], unique=False)
    op.drop_index(op.f('ix_member_username'), table_name='member')
    op.drop_index(op.f('ix_member_is_executive'), table_name='member')
    op.drop_column('member', 'username')
    op.drop_column('member', 'is_executive')
    op.drop_index(op.f('ix_event_title'), table_name='event')
    op.create_index('ix_event_title', 'event', ['title'], unique=1)
    # ### end Alembic commands ###
